project_name: Paperboy
version: 2

builds:
  - binary: paperboy
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    tags: ['{{ if index .Env "BUILD_WITH_UI" }}withUI{{ else }}noUI{{ end }}']

universal_binaries:
  - name_template: paperboy
    replace: true

archives:
  - formats: ["tar.gz"]
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: >-
      {{- .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{- title .Os }}{{ end }}_
      {{- if eq .Arch "all" }}universal
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  disable: true

release:
  draft: true
